### ISSUE TITLE
Wrong encoding when titles have accents

### ISSUE THREAD

**Issue by Algorithmus** [Steveice10/bannertool#18] opened 2019-04-23 22:27 UTC
Or any of the other fields with text. It causes 3DS themes with info.smdh made with bannertools to crash Anemone3DS.

So I fixed it by implementing utf8 to utf16 like this:

```
static void utf8_to_utf16(u16* dst, std::string src, size_t maxLen) {
    std::u16string utf16str = std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t>{}.from_bytes(src.data());

    if(maxLen == 0) {
        return;
    }

    size_t n = 0;
    while(src[n]) {
        dst[n] = (u16) utf16str[n];
        if(n++ >= maxLen) {
            return;
        }
}
}
```

Appears to work with more common accents and some Japanese.

**Comment by Steveice10** [comment] 2019-04-26 04:46
Looks like my original implementation was a quick job that just worked to convert characters with equivalent UTF-8 and UTF-16 values. I'll replace it with proper conversion soon.

**Comment by Steveice10** [comment] 2019-05-04 05:56
Sorry for the delay, this should be fixed now. Can you confirm that the issue is fixed?

**Comment by Algorithmus** [comment] 2019-05-04 10:05
Yes, it works now. Thanks.

**Closed** 2019-05-04 10:05 UTC
